/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from "@tanstack/react-start/server";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as authRouteRouteImport } from "./routes/(auth)/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as GameSamsungSdsRouteImport } from "./routes/game/samsung-sds";
import { Route as authSignupRouteImport } from "./routes/(auth)/signup";
import { Route as authLoginRouteImport } from "./routes/(auth)/login";
import { ServerRoute as ApiGameProgressServerRouteImport } from "./routes/api/game/progress";
import { ServerRoute as ApiGameCompleteServerRouteImport } from "./routes/api/game/complete";
import { ServerRoute as ApiAuthSplatServerRouteImport } from "./routes/api/auth/$";

const rootServerRouteImport = createServerRootRoute();

const authRouteRoute = authRouteRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const GameSamsungSdsRoute = GameSamsungSdsRouteImport.update({
  id: "/game/samsung-sds",
  path: "/game/samsung-sds",
  getParentRoute: () => rootRouteImport,
} as any);
const authSignupRoute = authSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => authRouteRoute,
} as any);
const authLoginRoute = authLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => authRouteRoute,
} as any);
const ApiGameProgressServerRoute = ApiGameProgressServerRouteImport.update({
  id: "/api/game/progress",
  path: "/api/game/progress",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiGameCompleteServerRoute = ApiGameCompleteServerRouteImport.update({
  id: "/api/game/complete",
  path: "/api/game/complete",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootServerRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof authRouteRouteWithChildren;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
  "/game/samsung-sds": typeof GameSamsungSdsRoute;
}
export interface FileRoutesByTo {
  "/": typeof authRouteRouteWithChildren;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
  "/game/samsung-sds": typeof GameSamsungSdsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/(auth)": typeof authRouteRouteWithChildren;
  "/(auth)/login": typeof authLoginRoute;
  "/(auth)/signup": typeof authSignupRoute;
  "/game/samsung-sds": typeof GameSamsungSdsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login" | "/signup" | "/game/samsung-sds";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/login" | "/signup" | "/game/samsung-sds";
  id:
    | "__root__"
    | "/"
    | "/(auth)"
    | "/(auth)/login"
    | "/(auth)/signup"
    | "/game/samsung-sds";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  authRouteRoute: typeof authRouteRouteWithChildren;
  GameSamsungSdsRoute: typeof GameSamsungSdsRoute;
}
export interface FileServerRoutesByFullPath {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/game/complete": typeof ApiGameCompleteServerRoute;
  "/api/game/progress": typeof ApiGameProgressServerRoute;
}
export interface FileServerRoutesByTo {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/game/complete": typeof ApiGameCompleteServerRoute;
  "/api/game/progress": typeof ApiGameProgressServerRoute;
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/game/complete": typeof ApiGameCompleteServerRoute;
  "/api/game/progress": typeof ApiGameProgressServerRoute;
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath;
  fullPaths: "/api/auth/$" | "/api/game/complete" | "/api/game/progress";
  fileServerRoutesByTo: FileServerRoutesByTo;
  to: "/api/auth/$" | "/api/game/complete" | "/api/game/progress";
  id: "__root__" | "/api/auth/$" | "/api/game/complete" | "/api/game/progress";
  fileServerRoutesById: FileServerRoutesById;
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute;
  ApiGameCompleteServerRoute: typeof ApiGameCompleteServerRoute;
  ApiGameProgressServerRoute: typeof ApiGameProgressServerRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(auth)": {
      id: "/(auth)";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof authRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/game/samsung-sds": {
      id: "/game/samsung-sds";
      path: "/game/samsung-sds";
      fullPath: "/game/samsung-sds";
      preLoaderRoute: typeof GameSamsungSdsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)/signup": {
      id: "/(auth)/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof authSignupRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    "/(auth)/login": {
      id: "/(auth)/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof authLoginRouteImport;
      parentRoute: typeof authRouteRoute;
    };
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/api/game/progress": {
      id: "/api/game/progress";
      path: "/api/game/progress";
      fullPath: "/api/game/progress";
      preLoaderRoute: typeof ApiGameProgressServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/game/complete": {
      id: "/api/game/complete";
      path: "/api/game/complete";
      fullPath: "/api/game/complete";
      preLoaderRoute: typeof ApiGameCompleteServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute;
  authSignupRoute: typeof authSignupRoute;
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
};

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  GameSamsungSdsRoute: GameSamsungSdsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiGameCompleteServerRoute: ApiGameCompleteServerRoute,
  ApiGameProgressServerRoute: ApiGameProgressServerRoute,
};
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>();
